### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by rathaROG** [jinfagang/DCNv2_latest#17]
Hello, I faced these issues:

```
../src/cuda/dcn_v2_cuda.cu(162): error: identifier "THCudaBlas_SgemmBatched" is undefined

../src/cuda/dcn_v2_cuda.cu(309): error: identifier "THCudaBlas_Sgemm" is undefined

../src/cuda/dcn_v2_cuda.cu(359): error: argument of type "long *" is incompatible with parameter of type "int64_t *"
```
My system: Anaconda with Python 3.6.12, Windows 10, Cuda 11.1.1, Pytorch 1.8

**Comment by jinfagang** [comment]
I have no problem on my 1.8 env:

```
pip list | grep torch                                         
torch                              1.8.0+cu111           
torchaudio                         0.8.0                 
torchvision                        0.9.0+cu111           

```

Please check on your side. Our lib can build on pytorch 1.8

**Comment by rathaROG** [comment]
> I have no problem on my 1.8 env:
> 
> ```
> pip list | grep torch                                         
> torch                              1.8.0+cu111           
> torchaudio                         0.8.0                 
> torchvision                        0.9.0+cu111           
> ```
> 
> Please check on your side. Our lib can build on pytorch 1.8

Hi, but did you successfully build on Ubuntu or Windows?
