### ISSUE TITLE
whypytorch 1.8, still  report RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by Hd-14** [jinfagang/DCNv2_latest#23]
i use pytorch1.8, cuda11.1, still report RuntimeError: Error compiling objects for extension

**Comment by jinfagang** [comment]
I have no issue with 1.8

**Comment by sunnyln** [comment]
@jinfagang I met the same error with python3.6, nvidia driver 460.73, cuda11.1, cudnn8.1.0, cudatoolkit11.1, pytorch1.8.0, gcc5.4.0. So I want to know what version of your other packages?

**Comment by jinfagang** [comment]
@sunnyln I have no issue on both pytorch1.8 and cuda11.
