### ISSUE TITLE
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 2

### ISSUE THREAD

**Issue by LiuHaodongdong** [jinfagang/DCNv2_latest#26]
Hi，thanks for your nice work.I have trouble when I try to build this work on my winsows10 PC with cuda 10.1,torch 1.4.0.Can you help me?

**Comment by jinfagang** [comment]
@LiuHaodongdong Please Baidu.
