### ISSUE TITLE
_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

### ISSUE THREAD

**Issue by qiuhaining** [jinfagang/DCNv2_latest#3]
hi,
some errors occured in my machine:
the info of my machine is:
`pytorch      1.5.0
os                ubuntu 14.04
cuda            10.1
driver           430.5`

my error is 
`  File "testcuda.py", line 11, in <module>
    from dcn_v2 import dcn_v2_conv, DCNv2, DCN
  File "/data/***/CenterNet_Online/src/lib/models/networks/DCNv2/dcn_v2.py", line 13, in <module>
    import _ext as _backend
ImportError: /data/***/CenterNet_Online/src/lib/models/networks/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument
`

**Comment by jinfagang** [comment]
could be your python problem.
