### ISSUE TITLE
does it support pytorch1.7 preview version?

### ISSUE THREAD

**Issue by splinter21** [jinfagang/DCNv2_latest#4]

**Comment by jinfagang** [comment]
Does pytorch 1.7 is out? Haven't tried it out, you can have a test, theoritically it should support.

**Comment by seovchinnikov** [comment]
They changed signatures in master in
https://github.com/pytorch/pytorch/blob/v1.5.1/aten/src/THC/THCBlas.h

so THCudaBlas_Sgemv is not here. So it won't work in 1.6+

**Comment by jinfagang** [comment]
@seovchinnikov PR is welcome to support pytorch 1.6+

**Comment by jinfagang** [comment]
@seovchinnikov @splinter21  You can check pytorch1.6 branch to support pytorch1.6+

**Comment by splinter21** [comment]
> @seovchinnikov @splinter21 You can check pytorch1.6 branch to support pytorch1.6+

Ok, thanks!

**Comment by austinmw** [comment]
Hi, any updates on 1.7 support?

**Comment by jinfagang** [comment]
@austinmw  You can try 1.6 branch? I suppose pytorch 1.7 should be same.

**Comment by austinmw** [comment]
1.6 built successfully but 1.7 failed for me

**Comment by jinfagang** [comment]
@austinmw Sure, I'll take some time to look, I shall upgrade to pytorch 1.7 as well.

**Comment by nostayup** [comment]
> @austinmw Sure, I'll take some time to look, I shall upgrade to pytorch 1.7 as well.

Looking forward to your upgrade, it will be very useful

**Comment by nmc-costa** [comment]
Hello, 

Thank you for the hard work, is it already update to pytorch 1.7?

**Comment by jinfagang** [comment]
@nmc-costa  Will upgrade this week

**Comment by jinfagang** [comment]
@nmc-costa Works on pytorch 1.7 now.

**Comment by nmc-costa** [comment]
@jinfagang Thank you so much for the hard work. I will give it a try.

**Comment by nmc-costa** [comment]
Just in case someone has problems building, beware of the the GCC version and NVCC version, if GCC>=7, then NVCC>=10.
