### ISSUE TITLE
Error in modulated_deformable_im2col_cuda

### ISSUE THREAD

**Issue by weilu1998** [jinfagang/DCNv2_latest#41]
Hi,

These error messages appeared when I started training using CenterTrack. My PyTorch version is 1.9 and I tried both CUDA versions 10.0/10.1/11.0. The error message appeared regardless of which CUDA version I use.

"
error in modulated_deformable_col2im_coord_cuda: invalid device function
error in modulated_deformable_col2im_cuda: invalid device function
error in modulated_deformable_im2col_cuda: invalid device function
"

**Comment by Armughan-Derq** [comment]
How did you guys solve this issue? I am also having the same problem
