### ISSUE TITLE
what's ATen?

### ISSUE THREAD

**Issue by shaqing** [jinfagang/DCNv2_latest#54]
i follow solution in #54, but i met this problem:
home/sti/kevin/work/smoke/SMOKE/smoke/csrc/cpu/dcn_v2_psroi_pooling_cpu.cpp:16:10: fatal error: ATen/ceil_div.h: No such file or directory
 #include <ATen/ceil_div.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by lucasjinreal** [comment]
please read readme first.

**Comment by juanmed** [comment]
Hi, I found the same problem as @shaqing  on the master branch using pytorch1.8.1+cuda111 Ubuntu18.04. When I try pytorch1.6 branch, I get the following error:

```
 error: ‘THFloatBlas_gemm’ was not declared in this scope
         THFloatBlas_gemm('n', 't', n, m, k, 1.0f,
```
I understand you tested on Ubuntu20 and recommend using pytorch1.11. I cannot change my pytorch/cuda so I was wondering if you have any comments?

**Comment by lucasjinreal** [comment]
Am not going support old pytorch anylonger, but you can switch to older branch for luck.

**Comment by juanmed** [comment]
I understand. Thank you very much!
