### ISSUE TITLE
No module named '_ext' 

### ISSUE THREAD

**Issue by s3unmo** [jinfagang/DCNv2_latest#70]

**Comment by lzzzzj** [comment]
Hello. Have you solved it? Meet the same problem.

**Comment by s3unmo** [comment]
换了环境然后就没报错



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 12, 2023 09:42 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [lucasjinreal/DCNv2_latest] No module named '_ext'  (Issue #70)




 
Hello. Have you solved it? Meet the same problem.

**Comment by HappySamuel** [comment]
Hi @s3unmo 
What do you mean by change environment? Can share the details steps?
