### ISSUE TITLE
LNK2001:   cublasSgemv_v2 undefined

### ISSUE THREAD

**Issue by parluo** [jinfagang/DCNv2_latest#8]
`dcn_v2_cuda.obj : error LNK2001: 无法解析的外部符号 cublasSgemv_v2

 build\lib.win-amd64-3.8\_ext.cp38-win_amd64.pyd : fatal error LNK1120: 1 个无法解析的外部命令

error: command 'D:\\Software\\VS2019\\VS2019\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120`

Is there anything wrong with my environment?

**Comment by jinfagang** [comment]
what's your pytorch version?

**Comment by parluo** [comment]
pytorch1.6+cuda11.1， and finally I used this [repo](https://github.com/half-potato/DCNv2)

**Comment by jinfagang** [comment]
@parluo  Pytorch 1.6 is supported in pytorch1.6 branch... Pls read readme first before open an issue..
